### ISSUE TITLE
1. INBOX SCRUB

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#52] opened 2015-10-24 05:55 UTC
## INBOX SCRUB

- [x] 1. Fix the duplication/mirroring issue in INBOX
 - See image below.
- [x] 2. Check the inbox avatar size. 
 -  They're loading slow and often out of order. Probably the same issues as activity avatar
- [x] 3. Request the following from Steve by creating an issue. 
  - Provide a utility endpoint for the conversation screen that checks for new messages every second. 
 - A user shouldn't have to go Conversation -> Inbox -> Conversation to read a message. 
- [x] 4. Clicking the inbox icon should redirect the user back to Inbox
  - **To replicate**
  - Go to inbox
  - Click conversation
  - Send a message
  - Dismiss keyboard 
  - Click inbox (<- At this stage the Inbox button should show you the inbox screen)
- [x] 5. On the compose screen the keyboard should be active. 
- [x] 6. Add the timestamps in the conversation screen. (Same link as below)
- [x] 7. Update the UI  [**IMPORTANT**]
 -  https://github.com/sceene/sprint-planning/issues/47
 - All the details are listed so please make sure it's updated. 

## (1.) MIRRORING ISSUE INBOX
![img_1937](https://cloud.githubusercontent.com/assets/12651511/10703600/fbf91eec-7985-11e5-9f71-f4bf417c71ef.PNG)

**Comment by joshrio** [comment] 2015-10-24 07:17
## CONVERSATION MEASUREMENTS

### TIMESTAMPS

Font size: 13px
Weight: Medium
RGB: 204, 204, 204

### SENDER CHAT @1x

Font Size: 16px
Line Height 1.50
Weight: Regular
RGB: 255, 255, 255
Chat Bubble: RGB: 125, 179, 246 
Chat Bubble Border Radius: 20px

### RECIEVER CHAT @1x

Font Size: 16px
Line Height 1.50
Weight: Regular
RGB: 255, 255, 255
Chat Bubble: RGB: 169, 169, 169
Chat Bubble Border Radius: 20px

### READ TIMESTAMP @1x

Font size: 10px
Weight: Medium
RGB: 204, 204, 204

*To activate the sent and read receipts a user must tap once on a chat bubble. It then pushes the chat bubble beneath it down 28px to display it*

### SENT TIMESTAMP @1x

Font size: 10px
Weight: Medium
RGB: 204, 204, 204
### TIMESTAMP UX 

*To activate the sent and read receipts a user must tap once on a chat bubble. It then pushes the chat bubble beneath it down 28px to display it*

### OPTIONS UX 

- A user I reveal additional options on a message by holding down on a message
- As a user I then select the option such as copy or delete 
- As a user if I select delete then I should see a pop up alert modal
- As a user the modal should say to me 
 - **Title**: Delete Message
 - **Message**: Are you sure you want to delete this message
 - **Options**: Yes No

## CONVERSATION MEASUREMENTS @2x

*Make sure you divider by 2 the measurements in these images as it's @2x* 

To explain each vertical measurement **PLEASE READ**

20px (10px @1x): Space between two users messages in the same day. 
68px (34px @1x): Space between two messages on different days.
24px (12px @1x): Space between timestamps baseline and the first message on that day.
8px (4px @1x): Space between two messages sent from he same person.
48px (24px @1x): Space between two messages when the users has activated the view read/sent receipts 
28px (14px @1x): Space between the baseline of a timestamp and the bottom messages
 - This is only activated when the user clicks on the message to view read/sent receipts
 - Look at FB Messenger to see this work. I took it from there. 
Not Shown: 32px (16px @1x): Space between the bottom of the last message and the message compose input field 


![conversation final_measurements](https://cloud.githubusercontent.com/assets/12651511/10616623/d7ab545a-771a-11e5-88d2-eac6f4e41471.png)

**Comment by joshrio** [comment] 2015-10-25 20:04
"#67" Endpoint to check for new conversations is complete.

Ping only when conversation window is open.
Ping no more than every 5 seconds

Enpoint:
/v1/communication/message

required params:

&communicationSender=
&communicationReceiver=
&keyword=last

Example:
http://api.sceene.com/v1/communication/message?key=oPKlL9P3XOdBWr2isnboRav27KKpMVrXNKtCARGf&communicationSender=12028621040350873762&communicationReceiver=12038015780276095138&keyword=last

**Comment by joshrio** [comment] 2015-10-25 21:01
## (1.) MIRRORING ISSUE INBOX
![img_1937](https://cloud.githubusercontent.com/assets/12651511/10703600/fbf91eec-7985-11e5-9f71-f4bf417c71ef.PNG)

**Comment by LucasCoelho** [comment] 2015-10-26 09:33
Hi @joshrio  
Concerning _1. Fix the duplication/mirroring issue in INBOX [BUG]_
Does it happen every single time with you?
I only had it once and I cannot reproduce it again. Would you know the steps to reproduce it? Thanks

**Comment by LucasCoelho** [comment] 2015-10-26 14:06
@joshrio concerning UI, I uploaded a build (173) for you to check what should be fixed. With the measurements you gave I can't really do much
Knowing that those measurements will probably change in a few weeks. I suggest we leave the fine tuning to one of the last things before launching

**Comment by joshrio** [comment] 2015-10-26 15:53
@LucasCoelho Yes. Every single time. 

https://youtu.be/Gea7lLcg9bM

**Comment by joshrio** [comment] 2015-10-26 15:55
@LucasCoelho I'm not to sure what you mean, but "you can't do much" with the measurements?

**Closed** 2015-10-28 01:07 UTC
Labels: HIGH PRIORITY
